server:
  port: 8082
spring:
  application:
    name: myHibernate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dxxy_test?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 60
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
logging:
  level:
    web: debug
